
services:
  base:
    image: ghcr.io/convince-project/moon:latest
    build:
      context: .
      dockerfile: .docker/Dockerfile
      # target: moon
    # Ensures signals are actually passed and reaped in the container for shutdowns.
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#init
    init: true
    # Interactive shell
    stdin_open: true
    tty: true
    # Networking and IPC for ROS 2
    network_mode: host
    ipc: host
    # Needed to run Groot inside the container
    privileged: true
    environment:
      # Ensure your ROS 2 system is only visible on the local network
      - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
      # If you disable ROS_LOCALHOST_ONLY above, ensure you use a unique domain ID on your network
      - ROS_DOMAIN_ID=0
      # Allows graphical programs in the container
      # - DISPLAY=${DISPLAY}
      # - QT_X11_NO_MITSHM=1
      # Enables FlexBE web UI to work as root inside the container
      - QTWEBENGINE_DISABLE_SANDBOX=1
    volumes:
      # Mount the workshop source code
      - ./:/MOON:rw
      # Allows graphical programs in the container
      # - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority

  # Runs tests
  # test:
  #   extends: base
  #   command: >
  #     bash -c "
  #       python3 -m pytest /colcon_ws/src/as2fm
  #     "
  #   profiles: [test]
